version: '3.8'

services:
  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/github_analysis
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: